name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarCloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache SonarCloud packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: Install SonarScanner
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9CDB294B29A5B1E2E00C24C022E8EF3461A50EF6
        echo 'deb https://debian.sonarsource.com/sonarqube/ stable main' | sudo tee -a /etc/apt/sources.list
        sudo apt-get update && sudo apt-get install -y sonar-scanner

    - name: SonarCloud Scan
      run: sonar-scanner \
        -Dsonar.projectKey=my:vulnerable-python-project \
        -Dsonar.sources=. \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=6202b6a99e3fb92d6ee14fac68b39fffb32856f7
